apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ryu-admin
  name: ryu-admin
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryu-admin
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ryu-admin
    spec:
      imagePullSecrets:
        - name: aliyun-docker
      containers:
        - name: ryu-admin
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/ryu-admin:SNAPSHOT-$BUILD_NUMBER
          ports:
            - containerPort: 8601
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "skywalking.blog:11800"
            - name: SW_AGENT_NAME
              value: "ryu-admin"
            - name: NACOS_ADDRESS
              value: nacos-o273.blog:8848
            - name: PRE
              value: prod
        - name: arthas
          image: hengyunabc/arthas
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 30; done;"]
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
      volumes:
        - name: shared-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ryu-admin
  name: ryu-admin
  namespace: blog
spec:
  ports:
    - name: http
      port: 8601
      protocol: TCP
      targetPort: 8601
  selector:
    app: ryu-admin
  sessionAffinity: None
  type: ClusterIP
