apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryu-monitor
  namespace: blog
spec:
  replicas: 1  # 期望的副本数
  selector:
    matchLabels:
      app: ryu-monitor
  template:
    metadata:
      labels:
        app: ryu-monitor
    spec:
      containers:
        - name: ryu-monitor
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/ryu-monitor:SNAPSHOT-$BUILD_NUMBER  # 替换为你的容器镜像地址
          ports:
            - containerPort: 8606  # 应用程序监听的端口
      imagePullSecrets:
        - name: aliyun-docker