apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ryu-search
  name: ryu-search
  namespace: blog
spec:
  replicas: 1  # 期望的副本数
  selector:
    matchLabels:
      app: ryu-search
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ryu-search
    spec:
      imagePullSecrets:
        - name: aliyun-docker
      containers:
        - name: ryu-search
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/ryu-search:SNAPSHOT-$BUILD_NUMBER  # 替换为你的容器镜像地址
          
          ports:
            - containerPort: 8605  # 应用程序监听的端口
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "skywalking.blog:11800"
            - name: SW_AGENT_NAME
              value: "ryu-search"
            - name: NACOS_ADDRESS
              value: nacos-o273.blog:8848
            - name: PRE
              value: prod

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ryu-search
  name: ryu-search
  namespace: blog
spec:
  ports:
    - name: http
      port: 8605
      protocol: TCP
      targetPort: 8605
  selector:
    app: ryu-search
  sessionAffinity: None
  type: ClusterIP