apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ryu-search
  name: ryu-search
  namespace: blog
spec:
  replicas: 1  # 期望的副本数
  selector:
    matchLabels:
      app: ryu-search
  strategy:
    rollingUpdate:
      maxsurge: 50%
      maxUnavailable: 50%
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: ryu-search
    spec:
      imagesPullSecrets:
        - name: aliyun-docker
      containers:
        - name: ryu-search
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/ryu-search:SNAPSHOT-$BUILD_NUMBER  # 替换为你的容器镜像地址
          ports:
            - containerPort: 8605  # 应用程序监听的端口
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ryu-search
  name: ryu-search
  namespace: blog
spec:
  ports:
    -name: http
    port: 8605
    protocol: TCP
    targetPort: 8605
  selector:
    app: ryu-search
    sessionAffinity: None
    type: ClusterIP