apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ryu-spider
  name: ryu-spider
  namespace: blog
spec:
  replicas: 1  # 期望的副本数
  selector:
    matchLabels:
      app: ryu-spider
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ryu-spider
    spec:
      imagePullSecrets:
        - name: aliyun-docker
      containers:
        - name: ryu-spider
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/ryu-spider:SNAPSHOT-$BUILD_NUMBER  # 替换为你的容器镜像地址
         
          ports:
            - containerPort: 8608  # 应用程序监听的端口
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "skywalking.blog:11800"
            - name: SW_AGENT_NAME
              value: "ryu-spider"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ryu-spider
  name: ryu-spider
  namespace: blog
spec:
  ports:
    - name: http
      port: 8608
      protocol: TCP
      targetPort: 8608
  selector:
    app: ryu-spider
  sessionAffinity: None
  type: ClusterIP