apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ryu-resource
  name: ryu-resource
  namespace: blog
spec:
  replicas: 1  # 期望的副本数
  selector:
    matchLabels:
      app: ryu-resource
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ryu-resource
    spec:
      imagePullSecrets:
        - name: aliyun-docker
      containers:
        - name: ryu-resource
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/ryu-resource:SNAPSHOT-$BUILD_NUMBER  # 替换为你的容器镜像地址
          
          ports:
            - containerPort: 8602  # 应用程序监听的端口
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "skywalking.blog:11800"
            - name: SW_AGENT_NAME
              value: "ryu-resource"
            - name: SERVER_ADDRESS
              value: nacos-o273.blog:8848
            - name: PRE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ryu-resource
  name: ryu-resource
  namespace: blog
spec:
  ports:
    - name: http
      port: 8602
      protocol: TCP
      targetPort: 8602
  selector:
    app: ryu-resource
  sessionAffinity: None
  type: ClusterIP