apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ryu-web
  name: ryu-web
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryu-web
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ryu-web
    spec:
      containers:
        - name: ryu-web
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/ryu-web:SNAPSHOT-$BUILD_NUMBER
          ports:
            - containerPort: 8603
      imagePullSecrets:
        - name: aliyun-docker
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ryu-web
  name: ryu-web
  namespace: blog
spec:
  ports:
    - name: http
      port: 8603
      protocol: TCP
      targetPort: 8603
  selector:
    app: ryu-web
  sessionAffinity: None
  type: ClusterIP
