apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ryu-admin
  name: ryu-admin
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryu-admin
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ryu-admin
    spec:
      containers:
        - name: ryu-admin
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/ryu-admin:SNAPSHOT-$BUILD_NUMBER
          envFrom:
          - configMapRef:
              name: your-config-map
          ports:
            - containerPort: 8601
      imagePullSecrets:
        - name: aliyun-docker
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ryu-admin
  name: ryu-admin
  namespace: blog
spec:
  ports:
    - name: http
      port: 8601
      protocol: TCP
      targetPort: 8601
  selector:
    app: ryu-admin
  sessionAffinity: None
  type: ClusterIP
