apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ryu-gateway
  name: ryu-gateway
  namespace: blog
spec:
  replicas: 1  # 期望的副本数
  selector:
    matchLabels:
      app: ryu-gateway
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: ryu-gateway
    spec:
      imagesPullSecrets:
        - name: aliyun-docker
      containers:
        - name: ryu-gateway
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/ryu-gateway:SNAPSHOT-$BUILD_NUMBER  # 替换为你的容器镜像地址
          ports:
            - containerPort: 8607  # 应用程序监听的端口
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ryu-gateway
  name: ryu-gateway
  namespace: blog
spec:
  ports:
    - name: http
      port: 8607
      protocol: TCP
      targetPort: 8607
  selector:
    app: ryu-gateway
  sessionAffinity: None
  type: ClusterIP