spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.52.229.31:3306/security_authority?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 475118582
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 106.52.229.31
    port: 6379
    password: 475118582

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info


